spring.application.name: hhplus-clean-arch-tdd-java
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      # 웹 콘솔에 접근 시 사용하는 경로 (기본 /h2-console)

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    open-in-view: false                # OSIV 비활성화
    show-sql: true                     # 콘솔에 쿼리 출력
    hibernate:
      ddl-auto: create-drop            # 테스트 시 매번 DDL 생성 후 제거
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true               # 쿼리를 보기 좋게 포맷팅
        default_batch_fetch_size: 50   # Batch Fetch Size 설정

logging:
  level:
    org.hibernate.SQL: DEBUG           # 쿼리 로그 레벨 설정
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
